### ISSUE TITLE
I've just found this userscript and I quite like it.

### ISSUE THREAD

**Issue by Wizek** [dogancelik/irccloud-auto-reconnect#1]
Hey, I wanted to express my appreciation that you've created it.

Thank you.

That's all; feel free to close this "issue". 😃

**Comment by dogancelik** [comment]
Wow thank you, I didn't think anyone would use this 😅😅

**Comment by Wizek** [comment]
😉

So, as little as I've used it so far, it seems that the reconnection only runs during startup, right? So if I leave IRCCloud open in the background, put my computer to sleep for the night, the script won't reconnect me in the morning, correct? At least this is what I've experienced so far.

And if so, would you be open to discussing how this reconnection might work. And/or accepting a pull request if I decide to implement it? The most straightforward (and potentially quite hackish) way I can think of achieving it is just to `setInterval(init, 60 * 1000)`. I haven't familiarized myself with the code enough to see if this may lead to code running that shouldn't run more than once. What do you think?

**Comment by dogancelik** [comment]
Reconnecting is only useful when you are *not* connected to these networks you choose. This is mostly useful for **free** users who want to connect to selected **disconnected** networks when they open their browser.

If you close your browser, IRCCloud will disconnect you after 2 hours (because you are *free* user), there is nothing this userscript can do about that.

If you are a paid IRCCloud subscriber, you don't have to worry about being disconnected because you are never disconnected after 2 hours like free IRCCloud users.

**Comment by Wizek** [comment]
> If you close your browser, IRCCloud will disconnect you after 2 hours (because you are free user), there is nothing this userscript can do about that.

Yes, I understand that, and that's okay for me.

But I'm not sure we are on the same page yet, so let me try to ask a few questions to help us better understand each other:

What happens if I don't close my browser and hibernate my computer for, say, 3 hours? IRCCloud will still disconnect after 2 hours, right? And when I wake my pc from hibernation, then I will stay disconnected, right?

**Comment by dogancelik** [comment]
When you hibernate your computer, it saves every program opened inside your RAM to a file named `hiberfil.sys` (if you use Windows). Then "closes" your computer temporarily so technically all of your programs are closed and sleeping and will come back as you left before when you power on your computer on again. (So it will transfer `hiberfil.sys` to your RAM back so you lose no work / data on your open programs.)

Because it will "close" your computer, it will not communicate with anything online / not talk to IRCCloud, so that's why IC will disconnect you on Hibernation too.

I think the most **peaceful way** *(to not disrupt their business model)* would be to keep your computer on, or keep IC open in a small computer that is always on like Raspberry Pi (a $15 Linux device).

**Comment by Wizek** [comment]
> Because it will "close" your computer, it will not communicate with anything online / not talk to IRCCloud, so that's why IC will disconnect you on Hibernation too.

Yes, I'm glad we are on the same page about this so far. 

> the most peaceful way (to not disrupt their business model) 

I don't think what I am proposing would make much of a difference for their business model. I'd still be disconnected after 2 hours of hibernation. If anything, if I were to invest in a RPi, that would put more load on their servers for my free account since I'd be using their resources even when they would disconnect me otherwise. Wouldn't you agree?

It's just when I wake my computer up, instead of having to remember to manually click the reconnect button (as would be the case if I wouldn't use your user script), or having to remember to manually refresh the browser tab (as is the case with how the current userscript works (isn't it?)), I'd like it to reconnect automatically.

Is it more clear now what I'd like to do, or do you perhaps have any questions?

**Comment by dogancelik** [comment]
If you subscribe to IC ($5 / month), you are never disconnected so you don't have to reconnect every time or keep your computer awake all the time. I'm sorry if I didn't understand it. I think if you liked IRCCloud, I would pay for it. You can access your IRC networks on phone, tablet & computer. It's a nice idea. Or you can use more advanced DIY software like [Quassel](http://quassel-irc.org/) or if you use IRC on PC only, [HexChat](https://hexchat.github.io/) would also suffice.

**Comment by Wizek** [comment]
So, I've made a small change to solve my problem: https://github.com/Wizek/irccloud-auto-reconnect/commit/60a7c5ef760ce1f530031af0c7d1ddb7a3dfd973?w=1
After brief testing, it seems like it works well.

Feel free to pull the change if you like it after all.

**Comment by dogancelik** [comment]
Thanks @Wizek for your interest, I think I will close and implement your feature / wish as an optional feature in script settings panel soon, so users can decide to activate it or not 😉

**Comment by Wizek** [comment]
Great, thanks!
